# Generated by Django 4.2.2 on 2023-06-13 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid Email')])),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(default='Images/None/Noimg.jpg', upload_to='images/')),
            ],
        ),
    ]
